### PR TITLE
Change readme

### PR DESCRIPTION
**Pull request by GTConnor**
I changed the readme file

### CODE REVIEW

**Review by GTRekter — CHANGES_REQUESTED** [review]
Can you add a table

**Comment by GTConnor** [comment]
> Can you add a table containing the status badge?

Sure thing :-)

**Review by GTRekter — CHANGES_REQUESTED** [review]
Hi I'm back! I'm sorry but i prefer its original layout.

**Review by GTRekter — APPROVED** [review]
Good job

**Review by GTRekter — APPROVED** [review]
I like it

**Pull request merged**
